#!/usr/bin/env python

import Net
import sys
import socket

class Client:
    def __init__(self, address):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.socket.settimeout(0.1)
        self.socket.connect(address)
        self.socket.settimeout(None)

    def write(self, data):
        Net.write(self.socket, data)

    def read(self):
        return Net.read(self.socket)

    def command(self, data):
        self.write(data)
        return self.read()

if len(sys.argv)<2:
    print('usage: eppyc port')
    exit(1)
port = int(sys.argv[1])

data = ''
for line in sys.stdin:
    data += line

try:
    client = Client(('localhost', port))
    res = client.command(data)
except socket.timeout:
    res = None

print res
