#!/usr/bin/env python

import Client
import sys

if len(sys.argv)<2:
    print('usage: eppyc path')
    exit(1)
path = sys.argv[1]

data = ''
for line in sys.stdin:
    data += line

if not data:
    exit(2)

try:
    client = Client.Client(path)
    res = client.command(data)
except:
    res = None
    exit(1)

print res
