#!/usr/bin/env python

import sys
import Response
from pprint import pprint

if len(sys.argv)<2:
    print('usage: testResponse command')
    exit(1)
command = sys.argv[1]

xml = ''
for line in sys.stdin:
    xml += line

response = Response.build(command, xml)
pprint(response.data)
